<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net481</TargetFramework>
        <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
        <AutomaticallyUseFrameworkAssemblies>false</AutomaticallyUseFrameworkAssemblies>
        <NoStdLib>true</NoStdLib>
        <AddAdditionalExplicitAssemblyReferences>false</AddAdditionalExplicitAssemblyReferences>

        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>

        <Version>1.4.9.0</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>

        <Description>Show Jipper's UI in Adofai</Description>
        <Company>Jongyeol</Company>
        <Copyright>Copyright © Jongyeol 2024-2026</Copyright>
    </PropertyGroup>

    <Target Name="GetReferenceAssemblyPaths"/>

    <PropertyGroup>
        <FrameworkPathOverride>$(GameManagedPath)</FrameworkPathOverride>
        <TargetFrameworkDirectory>$(GameManagedPath)</TargetFrameworkDirectory>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="0Harmony">
            <HintPath>$(GameManagedPath)/UnityModManager/0Harmony.dll</HintPath>
        </Reference>
        <Reference Include="Accessibility">
            <HintPath>$(GameManagedPath)/Accessibility.dll</HintPath>
        </Reference>
        <Reference Include="AdofaiTweaks">
            <HintPath>$(GameManagedPath)/../../Mods/AdofaiTweaks/AdofaiTweaks.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(GameManagedPath)/Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp-firstpass">
            <HintPath>$(GameManagedPath)/Assembly-CSharp-firstpass.dll</HintPath>
        </Reference>
        <Reference Include="com.rlabrecque.steamworks.net">
            <HintPath>$(GameManagedPath)/com.rlabrecque.steamworks.net.dll</HintPath>
        </Reference>
        <Reference Include="DemiLib">
            <HintPath>$(GameManagedPath)/DemiLib.dll</HintPath>
        </Reference>
        <Reference Include="dnlib">
            <HintPath>$(GameManagedPath)/UnityModManager/dnlib.dll</HintPath>
        </Reference>
        <Reference Include="DOTween">
            <HintPath>$(GameManagedPath)/DOTween.dll</HintPath>
        </Reference>
        <Reference Include="DOTweenPro">
            <HintPath>$(GameManagedPath)/DOTweenPro.dll</HintPath>
        </Reference>
        <Reference Include="I18N">
            <HintPath>$(GameManagedPath)/I18N.dll</HintPath>
        </Reference>
        <Reference Include="I18N.CJK">
            <HintPath>$(GameManagedPath)/I18N.CJK.dll</HintPath>
        </Reference>
        <Reference Include="I18N.MidEast">
            <HintPath>$(GameManagedPath)/I18N.MidEast.dll</HintPath>
        </Reference>
        <Reference Include="I18N.Other">
            <HintPath>$(GameManagedPath)/I18N.Other.dll</HintPath>
        </Reference>
        <Reference Include="I18N.Rare">
            <HintPath>$(GameManagedPath)/I18N.Rare.dll</HintPath>
        </Reference>
        <Reference Include="I18N.West">
            <HintPath>$(GameManagedPath)/I18N.West.dll</HintPath>
        </Reference>
        <Reference Include="JALib">
            <HintPath>$(GameManagedPath)/../../Mods/JALib/JALib.dll</HintPath>
        </Reference>
        <Reference Include="KeyboardChatterBlocker">
            <HintPath>$(GameManagedPath)/../../Mods/KeyboardChatterBlocker/KeyboardChatterBlocker.dll</HintPath>
        </Reference>
        <Reference Include="Mono.Data.Sqlite">
            <HintPath>$(GameManagedPath)/Mono.Data.Sqlite.dll</HintPath>
        </Reference>
        <Reference Include="Mono.Posix">
            <HintPath>$(GameManagedPath)/Mono.Posix.dll</HintPath>
        </Reference>
        <Reference Include="Mono.Security">
            <HintPath>$(GameManagedPath)/Mono.Security.dll</HintPath>
        </Reference>
        <Reference Include="Mono.WebBrowser">
            <HintPath>$(GameManagedPath)/Mono.WebBrowser.dll</HintPath>
        </Reference>
        <Reference Include="mscorlib">
            <HintPath>$(GameManagedPath)/mscorlib.dll</HintPath>
        </Reference>
        <Reference Include="netstandard">
            <HintPath>$(GameManagedPath)/netstandard.dll</HintPath>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(GameManagedPath)/Newtonsoft.Json.dll</HintPath>
        </Reference>
        <Reference Include="Novell.Directory.Ldap">
            <HintPath>$(GameManagedPath)/Novell.Directory.Ldap.dll</HintPath>
        </Reference>
        <Reference Include="Ookii.Dialogs">
            <HintPath>$(GameManagedPath)/Ookii.Dialogs.dll</HintPath>
        </Reference>
        <Reference Include="Purchasing.Common">
            <HintPath>$(GameManagedPath)/Purchasing.Common.dll</HintPath>
        </Reference>
        <Reference Include="RDTools">
            <HintPath>$(GameManagedPath)/RDTools.dll</HintPath>
        </Reference>
        <Reference Include="Rewired_Core">
            <HintPath>$(GameManagedPath)/Rewired_Core.dll</HintPath>
        </Reference>
        <Reference Include="Rewired_Windows">
            <HintPath>$(GameManagedPath)/Rewired_Windows.dll</HintPath>
        </Reference>
        <Reference Include="Rewired_Windows_Functions">
            <HintPath>$(GameManagedPath)/Rewired_Windows_Functions.dll</HintPath>
        </Reference>
        <Reference Include="SkyHook.Unity">
            <HintPath>$(GameManagedPath)/SkyHook.Unity.dll</HintPath>
        </Reference>
        <Reference Include="System">
            <HintPath>$(GameManagedPath)/System.dll</HintPath>
        </Reference>
        <Reference Include="System.ComponentModel.Composition">
            <HintPath>$(GameManagedPath)/System.ComponentModel.Composition.dll</HintPath>
        </Reference>
        <Reference Include="System.ComponentModel.DataAnnotations">
            <HintPath>$(GameManagedPath)/System.ComponentModel.DataAnnotations.dll</HintPath>
        </Reference>
        <Reference Include="System.Configuration">
            <HintPath>$(GameManagedPath)/System.Configuration.dll</HintPath>
        </Reference>
        <Reference Include="System.Core">
            <HintPath>$(GameManagedPath)/System.Core.dll</HintPath>
        </Reference>
        <Reference Include="System.Data">
            <HintPath>$(GameManagedPath)/System.Data.dll</HintPath>
        </Reference>
        <Reference Include="System.Data.DataSetExtensions">
            <HintPath>$(GameManagedPath)/System.Data.DataSetExtensions.dll</HintPath>
        </Reference>
        <Reference Include="System.Design">
            <HintPath>$(GameManagedPath)/System.Design.dll</HintPath>
        </Reference>
        <Reference Include="System.DirectoryServices">
            <HintPath>$(GameManagedPath)/System.DirectoryServices.dll</HintPath>
        </Reference>
        <Reference Include="System.Drawing">
            <HintPath>$(GameManagedPath)/System.Drawing.dll</HintPath>
        </Reference>
        <Reference Include="System.Drawing.Design">
            <HintPath>$(GameManagedPath)/System.Drawing.Design.dll</HintPath>
        </Reference>
        <Reference Include="System.EnterpriseServices">
            <HintPath>$(GameManagedPath)/System.EnterpriseServices.dll</HintPath>
        </Reference>
        <Reference Include="System.IO.Compression">
            <HintPath>$(GameManagedPath)/System.IO.Compression.dll</HintPath>
        </Reference>
        <Reference Include="System.IO.Compression.FileSystem">
            <HintPath>$(GameManagedPath)/System.IO.Compression.FileSystem.dll</HintPath>
        </Reference>
        <Reference Include="System.Net.Http">
            <HintPath>$(GameManagedPath)/System.Net.Http.dll</HintPath>
        </Reference>
        <Reference Include="System.Numerics">
            <HintPath>$(GameManagedPath)/System.Numerics.dll</HintPath>
        </Reference>
        <Reference Include="System.Runtime.CompilerServices.Unsafe">
            <HintPath>$(GameManagedPath)/System.Runtime.CompilerServices.Unsafe.dll</HintPath>
        </Reference>
        <Reference Include="System.Runtime.Serialization">
            <HintPath>$(GameManagedPath)/System.Runtime.Serialization.dll</HintPath>
        </Reference>
        <Reference Include="System.Runtime.Serialization.Formatters.Soap">
            <HintPath>$(GameManagedPath)/System.Runtime.Serialization.Formatters.Soap.dll</HintPath>
        </Reference>
        <Reference Include="System.Security">
            <HintPath>$(GameManagedPath)/System.Security.dll</HintPath>
        </Reference>
        <Reference Include="System.ServiceModel.Internals">
            <HintPath>$(GameManagedPath)/System.ServiceModel.Internals.dll</HintPath>
        </Reference>
        <Reference Include="System.Transactions">
            <HintPath>$(GameManagedPath)/System.Transactions.dll</HintPath>
        </Reference>
        <Reference Include="System.Web">
            <HintPath>$(GameManagedPath)/System.Web.dll</HintPath>
        </Reference>
        <Reference Include="System.Web.ApplicationServices">
            <HintPath>$(GameManagedPath)/System.Web.ApplicationServices.dll</HintPath>
        </Reference>
        <Reference Include="System.Web.Services">
            <HintPath>$(GameManagedPath)/System.Web.Services.dll</HintPath>
        </Reference>
        <Reference Include="System.Windows.Forms">
            <HintPath>$(GameManagedPath)/System.Windows.Forms.dll</HintPath>
        </Reference>
        <Reference Include="System.Xml"/>
        <Reference Include="System.Xml.Linq">
            <HintPath>$(GameManagedPath)/System.Xml.Linq.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Addressables">
            <HintPath>$(GameManagedPath)/Unity.Addressables.dll</HintPath>
        </Reference>
        <Reference Include="Unity.MemoryProfiler">
            <HintPath>$(GameManagedPath)/Unity.MemoryProfiler.dll</HintPath>
        </Reference>
        <Reference Include="Unity.ResourceManager">
            <HintPath>$(GameManagedPath)/Unity.ResourceManager.dll</HintPath>
        </Reference>
        <Reference Include="Unity.ScriptableBuildPipeline">
            <HintPath>$(GameManagedPath)/Unity.ScriptableBuildPipeline.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Analytics">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Analytics.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Configuration">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Configuration.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Device">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Device.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Environments">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Environments.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Environments.Internal">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Environments.Internal.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Internal">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Internal.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Networking">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Networking.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Registration">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Registration.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Scheduler">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Scheduler.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Telemetry">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Telemetry.dll</HintPath>
        </Reference>
        <Reference Include="Unity.Services.Core.Threading">
            <HintPath>$(GameManagedPath)/Unity.Services.Core.Threading.dll</HintPath>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>$(GameManagedPath)/Unity.TextMeshPro.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine">
            <HintPath>$(GameManagedPath)/UnityEngine.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AccessibilityModule">
            <HintPath>$(GameManagedPath)/UnityEngine.AccessibilityModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AIModule">
            <HintPath>$(GameManagedPath)/UnityEngine.AIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AndroidJNIModule">
            <HintPath>$(GameManagedPath)/UnityEngine.AndroidJNIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AnimationModule">
            <HintPath>$(GameManagedPath)/UnityEngine.AnimationModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ARModule">
            <HintPath>$(GameManagedPath)/UnityEngine.ARModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AssetBundleModule">
            <HintPath>$(GameManagedPath)/UnityEngine.AssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.AudioModule">
            <HintPath>$(GameManagedPath)/UnityEngine.AudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ClothModule">
            <HintPath>$(GameManagedPath)/UnityEngine.ClothModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ClusterInputModule">
            <HintPath>$(GameManagedPath)/UnityEngine.ClusterInputModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ClusterRendererModule">
            <HintPath>$(GameManagedPath)/UnityEngine.ClusterRendererModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ContentLoadModule">
            <HintPath>$(GameManagedPath)/UnityEngine.ContentLoadModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(GameManagedPath)/UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.CrashReportingModule">
            <HintPath>$(GameManagedPath)/UnityEngine.CrashReportingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.DirectorModule">
            <HintPath>$(GameManagedPath)/UnityEngine.DirectorModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.DSPGraphModule">
            <HintPath>$(GameManagedPath)/UnityEngine.DSPGraphModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GameCenterModule">
            <HintPath>$(GameManagedPath)/UnityEngine.GameCenterModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GIModule">
            <HintPath>$(GameManagedPath)/UnityEngine.GIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.GridModule">
            <HintPath>$(GameManagedPath)/UnityEngine.GridModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.HotReloadModule">
            <HintPath>$(GameManagedPath)/UnityEngine.HotReloadModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ImageConversionModule">
            <HintPath>$(GameManagedPath)/UnityEngine.ImageConversionModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule">
            <HintPath>$(GameManagedPath)/UnityEngine.IMGUIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>$(GameManagedPath)/UnityEngine.InputLegacyModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.InputModule">
            <HintPath>$(GameManagedPath)/UnityEngine.InputModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.JSONSerializeModule">
            <HintPath>$(GameManagedPath)/UnityEngine.JSONSerializeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.LocalizationModule">
            <HintPath>$(GameManagedPath)/UnityEngine.LocalizationModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.NVIDIAModule">
            <HintPath>$(GameManagedPath)/UnityEngine.NVIDIAModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ParticleSystemModule">
            <HintPath>$(GameManagedPath)/UnityEngine.ParticleSystemModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PerformanceReportingModule">
            <HintPath>$(GameManagedPath)/UnityEngine.PerformanceReportingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Physics2DModule">
            <HintPath>$(GameManagedPath)/UnityEngine.Physics2DModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PhysicsModule">
            <HintPath>$(GameManagedPath)/UnityEngine.PhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ProfilerModule">
            <HintPath>$(GameManagedPath)/UnityEngine.ProfilerModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.PropertiesModule">
            <HintPath>$(GameManagedPath)/UnityEngine.PropertiesModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Purchasing">
            <HintPath>$(GameManagedPath)/UnityEngine.Purchasing.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Purchasing.AppleCore">
            <HintPath>$(GameManagedPath)/UnityEngine.Purchasing.AppleCore.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Purchasing.AppleMacosStub">
            <HintPath>$(GameManagedPath)/UnityEngine.Purchasing.AppleMacosStub.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Purchasing.AppleStub">
            <HintPath>$(GameManagedPath)/UnityEngine.Purchasing.AppleStub.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Purchasing.Codeless">
            <HintPath>$(GameManagedPath)/UnityEngine.Purchasing.Codeless.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Purchasing.SecurityCore">
            <HintPath>$(GameManagedPath)/UnityEngine.Purchasing.SecurityCore.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Purchasing.SecurityStub">
            <HintPath>$(GameManagedPath)/UnityEngine.Purchasing.SecurityStub.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Purchasing.Stores">
            <HintPath>$(GameManagedPath)/UnityEngine.Purchasing.Stores.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Purchasing.WinRTCore">
            <HintPath>$(GameManagedPath)/UnityEngine.Purchasing.WinRTCore.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.Purchasing.WinRTStub">
            <HintPath>$(GameManagedPath)/UnityEngine.Purchasing.WinRTStub.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
            <HintPath>$(GameManagedPath)/UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.ScreenCaptureModule">
            <HintPath>$(GameManagedPath)/UnityEngine.ScreenCaptureModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SharedInternalsModule">
            <HintPath>$(GameManagedPath)/UnityEngine.SharedInternalsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SpriteMaskModule">
            <HintPath>$(GameManagedPath)/UnityEngine.SpriteMaskModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SpriteShapeModule">
            <HintPath>$(GameManagedPath)/UnityEngine.SpriteShapeModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.StreamingModule">
            <HintPath>$(GameManagedPath)/UnityEngine.StreamingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SubstanceModule">
            <HintPath>$(GameManagedPath)/UnityEngine.SubstanceModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.SubsystemsModule">
            <HintPath>$(GameManagedPath)/UnityEngine.SubsystemsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TerrainModule">
            <HintPath>$(GameManagedPath)/UnityEngine.TerrainModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TerrainPhysicsModule">
            <HintPath>$(GameManagedPath)/UnityEngine.TerrainPhysicsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextCoreFontEngineModule">
            <HintPath>$(GameManagedPath)/UnityEngine.TextCoreFontEngineModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextCoreTextEngineModule">
            <HintPath>$(GameManagedPath)/UnityEngine.TextCoreTextEngineModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>$(GameManagedPath)/UnityEngine.TextRenderingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TilemapModule">
            <HintPath>$(GameManagedPath)/UnityEngine.TilemapModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.TLSModule">
            <HintPath>$(GameManagedPath)/UnityEngine.TLSModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(GameManagedPath)/UnityEngine.UI.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIElementsModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UIElementsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UIModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UmbraModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UmbraModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityAnalyticsModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UnityAnalyticsModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityConnectModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UnityConnectModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityCurlModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UnityCurlModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityTestProtocolModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UnityTestProtocolModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestAudioModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UnityWebRequestModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestTextureModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.UnityWebRequestWWWModule">
            <HintPath>$(GameManagedPath)/UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VehiclesModule">
            <HintPath>$(GameManagedPath)/UnityEngine.VehiclesModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VFXModule">
            <HintPath>$(GameManagedPath)/UnityEngine.VFXModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VideoModule">
            <HintPath>$(GameManagedPath)/UnityEngine.VideoModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VirtualTexturingModule">
            <HintPath>$(GameManagedPath)/UnityEngine.VirtualTexturingModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.VRModule">
            <HintPath>$(GameManagedPath)/UnityEngine.VRModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.WindModule">
            <HintPath>$(GameManagedPath)/UnityEngine.WindModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.XRModule">
            <HintPath>$(GameManagedPath)/UnityEngine.XRModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityModManager">
            <HintPath>$(GameManagedPath)/UnityModManager/UnityModManager.dll</HintPath>
        </Reference>
        <Reference Include="XTUtilities">
            <HintPath>$(GameManagedPath)/XTUtilities.dll</HintPath>
        </Reference>
    </ItemGroup>

    <Target Name="CopyToModPath" AfterTargets="Build" Condition="'$(ModPath)' != ''">
        <Copy SourceFiles="$(OutputPath)JipperResourcePack.dll" DestinationFolder="$(ModPath)/JipperResourcePack" SkipUnchangedFiles="true"/>
        <Copy SourceFiles="$(OutputPath)JipperResourcePack.pdb" DestinationFolder="$(ModPath)/JipperResourcePack" Condition="Exists('$(OutputPath)JipperResourcePack.pdb')" SkipUnchangedFiles="true"/>
    </Target>

    <Target Name="CopyToReleasePath" AfterTargets="Build" Condition="'$(ReleasePath)' != '' and '$(Configuration)' == 'Release'">
        <Copy SourceFiles="$(OutputPath)JipperResourcePack.dll" DestinationFolder="$(ReleasePath)/JipperResourcePack" SkipUnchangedFiles="true"/>
    </Target>
</Project>
