//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JipperResourcePack.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        internal static string FinishScreen_CheckLog {
            get {
                return ResourceManager.GetString("FinishScreen_CheckLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jipper ResourcePack installation completed.
        ///Press the &apos;Exit&apos; button to finish the installation program..
        /// </summary>
        internal static string FinishScreen_Description {
            get {
                return ResourceManager.GetString("FinishScreen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the installation of the Jipper ResourcePack.
        ///Please press the &apos;View Log&apos; button to check for detailed errors..
        /// </summary>
        internal static string FinishScreen_Description_Error {
            get {
                return ResourceManager.GetString("FinishScreen_Description_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Adofai.
        /// </summary>
        internal static string FinishScreen_RunAdofai {
            get {
                return ResourceManager.GetString("FinishScreen_RunAdofai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jipper ResourcePack Installation Completed.
        /// </summary>
        internal static string FinishScreen_Title {
            get {
                return ResourceManager.GetString("FinishScreen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install Jipper ResourcePack.
        /// </summary>
        internal static string FinishScreen_Title_Error {
            get {
                return ResourceManager.GetString("FinishScreen_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Install_Finish {
            get {
                return ResourceManager.GetString("Install_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string Install_Install {
            get {
                return ResourceManager.GetString("Install_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Jipper ResourcePack on the Adofai.
        ///An Internet connection is required to do this.
        ///Press the &apos;Next&apos; button to continue..
        /// </summary>
        internal static string MainScreen_Description {
            get {
                return ResourceManager.GetString("MainScreen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to the Internet..
        /// </summary>
        internal static string MainScreen_NoInternet {
            get {
                return ResourceManager.GetString("MainScreen_NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Jipper ResourcePack starts the installation..
        /// </summary>
        internal static string MainScreen_Title {
            get {
                return ResourceManager.GetString("MainScreen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adofai folder guide.
        /// </summary>
        internal static string SelectLocation_AdofaiFolderGuide {
            get {
                return ResourceManager.GetString("SelectLocation_AdofaiFolderGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install the Jipper ResourcePack in the Adofai.
        ///If you install it in a different Adofai folder or if the program has not found the Adofai folder, click the &apos;Select Folder&apos; button to select the Adofai folder..
        /// </summary>
        internal static string SelectLocation_Description {
            get {
                return ResourceManager.GetString("SelectLocation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adofai Folder.
        /// </summary>
        internal static string SelectLocation_Location {
            get {
                return ResourceManager.GetString("SelectLocation_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected folder is not an Adofai folder..
        /// </summary>
        internal static string SelectLocation_NoAdofai {
            get {
                return ResourceManager.GetString("SelectLocation_NoAdofai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder does not exist..
        /// </summary>
        internal static string SelectLocation_NoFolder {
            get {
                return ResourceManager.GetString("SelectLocation_NoFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location is not set..
        /// </summary>
        internal static string SelectLocation_NoLocation {
            get {
                return ResourceManager.GetString("SelectLocation_NoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string SelectLocation_Select {
            get {
                return ResourceManager.GetString("SelectLocation_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the location of Adofai..
        /// </summary>
        internal static string SelectLocation_Title {
            get {
                return ResourceManager.GetString("SelectLocation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the mods you want to install..
        /// </summary>
        internal static string SelectMod_Description {
            get {
                return ResourceManager.GetString("SelectMod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Additional Mods.
        /// </summary>
        internal static string SelectMod_Mod {
            get {
                return ResourceManager.GetString("SelectMod_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select additional mods to install..
        /// </summary>
        internal static string SelectMod_Title {
            get {
                return ResourceManager.GetString("SelectMod_Title", resourceCulture);
            }
        }
    }
}
